<a href="https://colab.research.google.com/github/marivic9/EDA-CS-103/blob/main/Assignment_Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

In [ ]:
#packages

from pandas import read_csv
import pandas as pd

# Four different types of measurement scales described in statistics: nominal, ordinal, interval, and ratio.

# Datasets - train_and_test2, shanghai_ranking_2024, POP, and data

In [100]:
#first dataset - train_and_test2.csv
filename = 'train_and_test2.csv'
trainTest = read_csv('/gdrive/MyDrive/Colab Notebooks/statistics/train_and_test2.csv')
trainTest.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [101]:
#second dataset - train_and_test2.csv
filename = 'shanghai_ranking_2024.csv'
shanghaiRanking = read_csv('/gdrive/MyDrive/Colab Notebooks/statistics/shanghai_ranking_2024.csv')
shanghaiRanking.head()

,Rank,University_Name,National/Regional Rank,Alumni,Award,Hici,N&S,PUB,PCP
0,1,Harvard University,1,100.0,97.1,100.0,100.0,100.0,85.7
1,2,Stanford University,2,45.3,88.1,73.1,83.9,73.1,59.6
2,3,Massachusetts Institute of Technology (MIT),3,71.9,82.8,55.2,70.8,59.1,73.6
3,4,University of Cambridge,1,78.2,90.8,45.1,59.8,67.2,60.6
4,5,"University of California, Berkeley",4,65.3,76.5,46.9,62.8,57.1,55.5

In [102]:
#third dataset - POP.csv
filename = 'POP.csv'
POP = read_csv('/gdrive/MyDrive/Colab Notebooks/statistics/POP.csv')
POP.head()

   IND  1          India   1,417,173  Unnamed: 4
0  CHN  2          China   1,412,175         NaN
1  USA  3  United States     333,288         NaN
2  IDN  4      Indonesia     275,501         NaN
3  PAK  5       Pakistan     235,825         NaN
4  NGA  6        Nigeria     218,541         NaN

In [103]:
#fourth dataset - data.csv
filename = 'data.csv'
data = read_csv('/gdrive/MyDrive/Colab Notebooks/statistics/data.csv')
data.head()

,Position,Track Name,Artist,Streams,URL,Date,Region
0,1,Reggaetón Lento (Bailemos),CNCO,19272,https://open.spotify.com/track/3AEZUABDXNtecAO...,2017-01-01,ec
1,2,Chantaje,Shakira,19270,https://open.spotify.com/track/6mICuAdrwEjh6Y6...,2017-01-01,ec
2,3,Otra Vez (feat. J Balvin),Zion & Lennox,15761,https://open.spotify.com/track/3QwBODjSEzelZyV...,2017-01-01,ec
3,4,Vente Pa' Ca,Ricky Martin,14954,https://open.spotify.com/track/7DM4BPaS7uofFul...,2017-01-01,ec
4,5,Safari,J Balvin,14269,https://open.spotify.com/track/6rQSrBHf7HlZjtc...,2017-01-01,ec

In [129]:
trainTest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  1309 non-null   int64
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64
 4   sibsp        1309 non-null   int64
 5   zero         1309 non-null   int64
 6   zero.1       1309 non-null   int64
 7   zero.2       1309 non-null   int64
 8   zero.3       1309 non-null   int64
 9   zero.4       1309 non-null   int64
 10  zero.5       1309 non-null   int64
 11  zero.6       1309 non-null   int64
 12  Parch        1309 non-null   int64
 13  zero.7       1309 non-null   int64
 14  zero.8       1309 non-null   int64
 15  zero.9       1309 non-null   int64
 16  zero.10      1309 non-null   int64
 17  zero.11      1309 non-null   int64
 18  zero.12      1309 non-null   int64
 19  zero.13      1309 non-null   int64
 20  zero.14      1309 non-null   int64
 21  Pclass       1309 non-null   int64
 22  zero.15      1309 non-null   int64
 23  zero.16      1309 non-null   int64
 24  Embarked     1307 non-null   float64
 25  zero.17      1309 non-null   int64
 26  zero.18      1309 non-null   int64
 27  2urvived     1309 non-null   int64
dtypes: float64(3), int64(25)
memory usage: 286.5 KB

In [130]:
shanghaiRanking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Rank                    1000 non-null   object
 1   University_Name         1000 non-null   object
 2   National/Regional Rank  1000 non-null   object
 3   Alumni                  1000 non-null   float64
 4   Award                   1000 non-null   float64
 5   Hici                    1000 non-null   float64
 6   N&S                     989 non-null    float64
 7   PUB                     1000 non-null   float64
 8   PCP                     1000 non-null   float64
dtypes: float64(6), object(3)
memory usage: 70.4+ KB

In [131]:
POP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231 entries, 0 to 230
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   IND          228 non-null    object
 1   1            231 non-null    int64
 2   India        228 non-null    object
 3    1,417,173   228 non-null    object
 4   Unnamed: 4   2 non-null      object
dtypes: int64(1), object(4)
memory usage: 9.1+ KB

In [132]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3441197 entries, 0 to 3441196
Data columns (total 7 columns):
 #   Column      Dtype
---  ------      -----
 0   Position    int64
 1   Track Name  object
 2   Artist      object
 3   Streams     int64
 4   URL         object
 5   Date        object
 6   Region      object
dtypes: int64(2), object(5)
memory usage: 183.8+ MB

# **NOMINAL**

In [125]:
#Check for nominal variables in each dataset
nominal_variables_trainTest = trainTest.select_dtypes(include=['object']).columns
print("Nominal variables in trainTest:", nominal_variables_trainTest)

nominal_variables_shanghaiRanking = shanghaiRanking.select_dtypes(include=['object']).columns
print("Nominal variables in shanghaiRanking:", nominal_variables_shanghaiRanking)

nominal_variables_POP = POP.select_dtypes(include=['object']).columns
print("Nominal variables in POP:", nominal_variables_POP)

nominal_variables_data = data.select_dtypes(include=['object']).columns
print("Nominal variables in data:", nominal_variables_data)

Nominal variables in trainTest: Index([], dtype='object')
Nominal variables in shanghaiRanking: Index(['Rank', 'University_Name', 'National/Regional Rank'], dtype='object')
Nominal variables in POP: Index(['IND', 'India', ' 1,417,173 ', 'Unnamed: 4'], dtype='object')
Nominal variables in data: Index(['Track Name', 'Artist', 'URL', 'Date', 'Region'], dtype='object')

# **ORDINAL**

In [139]:
categorical_cols = trainTest.select_dtypes(include=['object', 'category']).columns

for col in categorical_cols:
  if len(df[col].unique()) < 10:
    print(f"Potential ordinal column: {col}")

print(categorical_cols)

Index([], dtype='object')

In [146]:
categorical_cols = shanghaiRanking.select_dtypes(include=['object', 'category']).columns

for col in categorical_cols:
  if len(shanghaiRanking[col].unique()) < 10:
    print(f"Potential ordinal column: {col}")

print(categorical_cols)

Index(['Rank', 'University_Name', 'National/Regional Rank'], dtype='object')

In [143]:
categorical_cols = POP.select_dtypes(include=['object', 'category']).columns

for col in categorical_cols:
  if len(POP[col].unique()) < 10:
    print(f"Potential ordinal column: {col}")

print(categorical_cols)

Potential ordinal column: Unnamed: 4
Index(['IND', 'India', ' 1,417,173 ', 'Unnamed: 4'], dtype='object')

In [144]:
categorical_cols = data.select_dtypes(include=['object', 'category']).columns

for col in categorical_cols:
  if len(data[col].unique()) < 10:
    print(f"Potential ordinal column: {col}")

print(categorical_cols)

Index(['Track Name', 'Artist', 'URL', 'Date', 'Region'], dtype='object')

# **INTERVAL**

In [150]:
def potential_interval_cols(df):
  potential_interval = []
  for col in df.columns:
    if df[col].dtype in ['int64', 'float64']:
      potential_interval.append(col)
  return potential_interval

potential_interval_trainTest = potential_interval_cols(trainTest)
print("Potential interval variables in trainTest:", potential_interval_trainTest)

potential_interval_shanghaiRanking = potential_interval_cols(shanghaiRanking)
print("Potential interval variables in shanghaiRanking:", potential_interval_shanghaiRanking)

potential_interval_POP = potential_interval_cols(POP)
print("Potential interval variables in POP:", potential_interval_POP)

potential_interval_data = potential_interval_cols(data)
print("Potential interval variables in data:", potential_interval_data)

for col in potential_interval_trainTest:
  print(f"Descriptive statistics for {col} in trainTest:")
  print(trainTest[col].describe())

for col in potential_interval_shanghaiRanking:
  print(f"Descriptive statistics for {col} in shanghaiRanking:")
  print(shanghaiRanking[col].describe())

for col in potential_interval_POP:
  print(f"Descriptive statistics for {col} in POP:")
  print(POP[col].describe())

for col in potential_interval_data:
  print(f"Descriptive statistics for {col} in data:")
  print(data[col].describe())

Potential interval variables in trainTest: ['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'zero', 'zero.1', 'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7', 'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13', 'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17', 'zero.18', '2urvived']
Potential interval variables in shanghaiRanking: ['Alumni', 'Award', 'Hici', 'N&S', 'PUB', 'PCP']
Potential interval variables in POP: ['1']
Potential interval variables in data: ['Position', 'Streams']
Descriptive statistics for Passengerid in trainTest:
count    1309.000000
mean      655.000000
std       378.020061
min         1.000000
25%       328.000000
50%       655.000000
75%       982.000000
max      1309.000000
Name: Passengerid, dtype: float64
Descriptive statistics for Age in trainTest:
count    1309.000000
mean       29.503186
std        12.905241
min         0.170000
25%        22.000000
50%        28.000000
75%        35.000000
max        80.000000
Name: Age, dtype: float64
Descriptive statistics for Fare in trainTest:
count    1309.000000
mean       33.281086
std        51.741500
min         0.000000
25%         7.895800
50%        14.454200
75%        31.275000
max       512.329200
Name: Fare, dtype: float64
Descriptive statistics for Sex in trainTest:
count    1309.000000
mean        0.355997
std         0.478997
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000
Name: Sex, dtype: float64
Descriptive statistics for sibsp in trainTest:
count    1309.000000
mean        0.498854
std         1.041658
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         8.000000
Name: sibsp, dtype: float64
Descriptive statistics for zero in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero, dtype: float64
Descriptive statistics for zero.1 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.1, dtype: float64
Descriptive statistics for zero.2 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.2, dtype: float64
Descriptive statistics for zero.3 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.3, dtype: float64
Descriptive statistics for zero.4 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.4, dtype: float64
Descriptive statistics for zero.5 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.5, dtype: float64
Descriptive statistics for zero.6 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.6, dtype: float64
Descriptive statistics for Parch in trainTest:
count    1309.000000
mean        0.385027
std         0.865560
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         9.000000
Name: Parch, dtype: float64
Descriptive statistics for zero.7 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.7, dtype: float64
Descriptive statistics for zero.8 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.8, dtype: float64
Descriptive statistics for zero.9 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.9, dtype: float64
Descriptive statistics for zero.10 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.10, dtype: float64
Descriptive statistics for zero.11 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.11, dtype: float64
Descriptive statistics for zero.12 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.12, dtype: float64
Descriptive statistics for zero.13 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.13, dtype: float64
Descriptive statistics for zero.14 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.14, dtype: float64
Descriptive statistics for Pclass in trainTest:
count    1309.000000
mean        2.294882
std         0.837836
min         1.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         3.000000
Name: Pclass, dtype: float64
Descriptive statistics for zero.15 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.15, dtype: float64
Descriptive statistics for zero.16 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.16, dtype: float64
Descriptive statistics for Embarked in trainTest:
count    1307.000000
mean        1.492731
std         0.814626
min         0.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         2.000000
Name: Embarked, dtype: float64
Descriptive statistics for zero.17 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.17, dtype: float64
Descriptive statistics for zero.18 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.18, dtype: float64
Descriptive statistics for 2urvived in trainTest:
count    1309.000000
mean        0.261268
std         0.439494
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000
Name: 2urvived, dtype: float64
Descriptive statistics for Alumni in shanghaiRanking:
count    1000.000000
mean        4.509600
std        10.103201
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       100.000000
Name: Alumni, dtype: float64
Descriptive statistics for Award in shanghaiRanking:
count    1000.00000
mean        3.78120
std        11.45538
min         0.00000
25%         0.00000
50%         0.00000
75%         0.00000
max       100.00000
Name: Award, dtype: float64
Descriptive statistics for Hici in shanghaiRanking:
count    1000.000000
mean       10.734400
std        10.949265
min         0.000000
25%         0.000000
50%         9.200000
75%        14.600000
max       100.000000
Name: Hici, dtype: float64
Descriptive statistics for N&S in shanghaiRanking:
count    989.000000
mean      10.575126
std       10.637247
min        0.000000
25%        3.900000
50%        7.300000
75%       13.300000
max      100.000000
Name: N&S, dtype: float64
Descriptive statistics for PUB in shanghaiRanking:
count    1000.000000
mean       35.113000
std        13.684495
min         9.300000
25%        25.775000
50%        31.700000
75%        41.425000
max       100.000000
Name: PUB, dtype: float64
Descriptive statistics for PCP in shanghaiRanking:
count    1000.000000
mean       19.655300
std         8.800436
min         8.600000
25%        14.100000
50%        17.600000
75%        23.000000
max       100.000000
Name: PCP, dtype: float64
Descriptive statistics for 1 in POP:
count    231.000000
mean     117.000000
std       66.828138
min        2.000000
25%       59.500000
50%      117.000000
75%      174.500000
max      232.000000
Name: 1, dtype: float64
Descriptive statistics for Position in data:
count    3.441197e+06
mean     9.464399e+01
std      5.739567e+01
min      1.000000e+00
25%      4.500000e+01
50%      9.200000e+01
75%      1.430000e+02
max      2.000000e+02
Name: Position, dtype: float64
Descriptive statistics for Streams in data:
count    3.441197e+06
mean     5.189176e+04
std      2.018035e+05
min      1.001000e+03
25%      3.322000e+03
50%      9.227000e+03
75%      2.965800e+04
max      1.138152e+07
Name: Streams, dtype: float64

# **RATIO**

In [151]:
def potential_ratio_cols(df):
  potential_ratio = []
  for col in df.columns:
    if df[col].dtype in ['int64', 'float64']:

      if df[col].min() == 0 or df[col].min() < 1e-6:
        potential_ratio.append(col)
  return potential_ratio

potential_ratio_trainTest = potential_ratio_cols(trainTest)
print("Potential ratio variables in trainTest:", potential_ratio_trainTest)

potential_ratio_shanghaiRanking = potential_ratio_cols(shanghaiRanking)
print("Potential ratio variables in shanghaiRanking:", potential_ratio_shanghaiRanking)

potential_ratio_POP = potential_ratio_cols(POP)
print("Potential ratio variables in POP:", potential_ratio_POP)

potential_ratio_data = potential_ratio_cols(data)
print("Potential ratio variables in data:", potential_ratio_data)

for col in potential_ratio_trainTest:
  print(f"Descriptive statistics for {col} in trainTest:")
  print(trainTest[col].describe())

for col in potential_ratio_shanghaiRanking:
  print(f"Descriptive statistics for {col} in shanghaiRanking:")
  print(shanghaiRanking[col].describe())

for col in potential_ratio_POP:
  print(f"Descriptive statistics for {col} in POP:")
  print(POP[col].describe())

for col in potential_data:
  print(f"Descriptive statistics for {col} in data:")
  print(data[col].describe())

Potential ratio variables in trainTest: ['Fare', 'Sex', 'sibsp', 'zero', 'zero.1', 'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7', 'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13', 'zero.14', 'zero.15', 'zero.16', 'Embarked', 'zero.17', 'zero.18', '2urvived']
Potential ratio variables in shanghaiRanking: ['Alumni', 'Award', 'Hici', 'N&S']
Potential ratio variables in POP: []
Potential ratio variables in data: []
Descriptive statistics for Fare in trainTest:
count    1309.000000
mean       33.281086
std        51.741500
min         0.000000
25%         7.895800
50%        14.454200
75%        31.275000
max       512.329200
Name: Fare, dtype: float64
Descriptive statistics for Sex in trainTest:
count    1309.000000
mean        0.355997
std         0.478997
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000
Name: Sex, dtype: float64
Descriptive statistics for sibsp in trainTest:
count    1309.000000
mean        0.498854
std         1.041658
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         8.000000
Name: sibsp, dtype: float64
Descriptive statistics for zero in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero, dtype: float64
Descriptive statistics for zero.1 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.1, dtype: float64
Descriptive statistics for zero.2 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.2, dtype: float64
Descriptive statistics for zero.3 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.3, dtype: float64
Descriptive statistics for zero.4 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.4, dtype: float64
Descriptive statistics for zero.5 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.5, dtype: float64
Descriptive statistics for zero.6 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.6, dtype: float64
Descriptive statistics for Parch in trainTest:
count    1309.000000
mean        0.385027
std         0.865560
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         9.000000
Name: Parch, dtype: float64
Descriptive statistics for zero.7 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.7, dtype: float64
Descriptive statistics for zero.8 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.8, dtype: float64
Descriptive statistics for zero.9 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.9, dtype: float64
Descriptive statistics for zero.10 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.10, dtype: float64
Descriptive statistics for zero.11 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.11, dtype: float64
Descriptive statistics for zero.12 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.12, dtype: float64
Descriptive statistics for zero.13 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.13, dtype: float64
Descriptive statistics for zero.14 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.14, dtype: float64
Descriptive statistics for zero.15 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.15, dtype: float64
Descriptive statistics for zero.16 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.16, dtype: float64
Descriptive statistics for Embarked in trainTest:
count    1307.000000
mean        1.492731
std         0.814626
min         0.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         2.000000
Name: Embarked, dtype: float64
Descriptive statistics for zero.17 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.17, dtype: float64
Descriptive statistics for zero.18 in trainTest:
count    1309.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: zero.18, dtype: float64
Descriptive statistics for 2urvived in trainTest:
count    1309.000000
mean        0.261268
std         0.439494
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000
Name: 2urvived, dtype: float64
Descriptive statistics for Alumni in shanghaiRanking:
count    1000.000000
mean        4.509600
std        10.103201
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       100.000000
Name: Alumni, dtype: float64
Descriptive statistics for Award in shanghaiRanking:
count    1000.00000
mean        3.78120
std        11.45538
min         0.00000
25%         0.00000
50%         0.00000
75%         0.00000
max       100.00000
Name: Award, dtype: float64
Descriptive statistics for Hici in shanghaiRanking:
count    1000.000000
mean       10.734400
std        10.949265
min         0.000000
25%         0.000000
50%         9.200000
75%        14.600000
max       100.000000
Name: Hici, dtype: float64
Descriptive statistics for N&S in shanghaiRanking:
count    989.000000
mean      10.575126
std       10.637247
min        0.000000
25%        3.900000
50%        7.300000
75%       13.300000
max      100.000000
Name: N&S, dtype: float64

NameError: name 'potential_data' is not defined